cronjob: Use system DTC again
Debian's packaged 1.4.0+dfsg-1 is now good enough.

diff --git a/scripts/cronjob b/scripts/cronjob
--- a/scripts/cronjob
+++ b/scripts/cronjob
@@ -92,7 +92,7 @@ fi
 echo
 
 make clean -s
-make DTC=/home/ianc/devel/dtc/dtc -k -s || true # This almost always fails...
+make -k -s || true # This almost always fails...
 echo
 echo "Test complete"
 echo
